# Generated by Django 3.2.18 on 2023-04-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('選択式', '選択'), ('真偽値', '真偽'), ('数字', '数字')], max_length=10),
        ),
    ]
