# Generated by Django 3.2.18 on 2023-03-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_food', models.CharField(choices=[('none', '無し'), ('a bit', '少し'), ('normal', '普通'), ('a lot', 'たくさん')], max_length=10)),
                ('fried_food', models.CharField(choices=[('none', '無し'), ('a bit', '少し'), ('normal', '普通'), ('a lot', 'たくさん')], max_length=10)),
                ('could_control_appetite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
