# Generated by Django 3.2.18 on 2023-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_answer_answer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='answer3',
            new_name='answer3_choice',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='answer4',
            new_name='answer4_choice',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer2',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer1_bool',
            field=models.BooleanField(choices=[(True, 'はい')], null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer1_choice',
            field=models.CharField(blank=True, choices=[('ゼロ', 'ゼロ')], max_length=10),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2_bool',
            field=models.BooleanField(choices=[(False, 'いいえ')], null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer2_choice',
            field=models.CharField(blank=True, choices=[('少し', '少し')], max_length=10),
        ),
    ]
