# Generated by Django 3.2.18 on 2023-04-01 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230331_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allergy', models.BooleanField(default=False)),
                ('is_unnecessary', models.BooleanField(default=False)),
                ('answer_type', models.CharField(max_length=255)),
                ('answer_choice', models.CharField(choices=[('none', '無し'), ('a bit', '少し'), ('normal', '普通'), ('a lot', 'たくさん')], max_length=10, null=True)),
                ('answer_int', models.IntegerField(null=True)),
                ('answer_bool', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mealquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Vegetable',
            new_name='MealVegetable',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.AddField(
            model_name='mealuser',
            name='vegetable_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mealvegetable'),
        ),
    ]
