# Generated by Django 3.2.18 on 2023-04-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230427_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer1_bool',
            field=models.BooleanField(blank=True, choices=[(True, 'はい')], null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer2_bool',
            field=models.BooleanField(blank=True, choices=[(False, 'いいえ')], null=True),
        ),
    ]
