# Generated by Django 3.2.18 on 2023-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230427_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer1_choice',
            field=models.CharField(blank=True, choices=[('ゼロ', 'ゼロ'), ('だるい', 'だるい')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer2_choice',
            field=models.CharField(blank=True, choices=[('少し', '少し'), ('少しだるい', '少しだるい')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer3_choice',
            field=models.CharField(blank=True, choices=[('まあまあ', 'まあまあ'), ('普通', '普通')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer4_choice',
            field=models.CharField(blank=True, choices=[('たくさん', 'たくさん'), ('良い', '良い')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
