# Generated by Django 3.2.18 on 2023-04-18 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230401_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mealquestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SleepUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(max_length=255)),
                ('answer_choice', models.CharField(max_length=10, null=True)),
                ('answer_int', models.IntegerField(null=True)),
                ('answer_bool', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sleep_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sleepquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
